# pdf_rag_task:
#   description: >
#     Analyze the PDF file 
#   expected_output: >
#     A clear, well-documented, and accurate answer to the question: {question}



pdf_reader_task:
  description: >
    Read the PDF file and extract text content
  expected_output: >
    Text extracted from PDF file, formatted as markdown without '```'.
    Save the file.


resume_analyst_task:
  description: >
    Analyze and thoroughly understand the context to generate output and answer: {question}
  expected_output: >
    A list with 10 bullet points of the candidate's key highlights and 
    A summary of what this candidate's strongest virtue and
    An answer to the question: {question}
    Formatted as markdown without '```'.
    If the tool does not provide a final answer after 3 attempts, stop using it and proceed with what you have.